name: Python test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Python環境のセットアップ
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: パッケージのインストール
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
      - name: flake8による検査
        run: |
          flake8 . --count --show-source --statistics --exclude=./test_*.py
      - name: テストファイルの一覧
        run: ls ./test_*.py
      - name: 単体テスト
        continue-on-error: true
        run: |
          pytest test_*.py --junitxml='test-report.xml'
      - uses: actions/upload-artifact@v3.1.0
        with:
          name: test-result
          path: './test-report.xml'
      - name: JUnit Report Action
        uses: mikepenz/action-junit-report@v3.1.0-b01
        with:
          report_paths: ./test-report.xml
